### ISSUE TITLE
cant enablee

### ISSUE THREAD

**Issue by manofthepeople** [natapol2547/paintsystem#36]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\Ibrahim\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\out\__init__.py", line 16, in <module>
    from .properties import update_active_image
  File "C:\Users\Ibrahim\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\out\properties.py", line 10, in <module>
    from bpy.types import (PropertyGroup, Context,
ImportError: cannot import name 'NodeTreeInterface' from 'bpy.types' (unknown location)

 is error when enabling

**Comment by natapol2547** [comment]
Paint system does not currently support Blender 3.4 😭 It only works on 4.1 and newer only.

**Comment by natapol2547** [comment]
I will close this issue. Let me know if you have any further problems with the addon!
